version: "3"

services:

  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"

  db:
    image: postgres:16-alpine
    restart: on-failure # перезагружает контейнер при падении
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose: # Вместо ports, чтобы исключить возможность попасть из вне
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata # из документации
    healthcheck: # проверка postgres готов в работе или нет
      test: ["CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER"]
      interval: 10s # Интервал опроса postgres
      retries: 5 # количестов попыток опроса postgres
      timeout: 5s # время одного опроса, после которого идет следущая попытка

  app:
    build: .
    tty: true # вкл интерактивный режим
    ports:
      - "8000:8000"

    # Команда для запуска (из Deckerfile необходимо удалить)
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on: # зависимости
      db:
        condition: service_healthy # состояние сервиса / сервис здоров
    volumes:
      - .:/app
    env_file:
      - .env

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - app


  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - app


volumes: # необходим чтобы при перезапуске не терялись данные из бд
  pg_data:
